service: aws-lambda-plain-java

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-1

package:
  artifact: build/libs/aws-lambda-plain-java-1.0.jar

functions:
  app:
    handler: StreamLambdaHandler::handleRequest
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
